{% set version = "5.5" %}

package:
  name: lpsolve55
  version: {{ version }}

source:
  git_url: https://github.com/chandu-atina/lp_solve_python_3x.git
  git_rev: 0b42fcd248a6b8b40e5f43ab759904a1f47720d4

build:
  number: 1004
  script: "{{ PYTHON }} -m pip install extra/Python -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy
    - lp_solve
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - lp_solve

test:
  imports:
    - lpsolve55

about:
  home: https://github.com/chandu-atina/lp_solve_python_3x
  license: LGPL
  license_file: LICENSE
  summary: lpsolve python extension for python 2.x and python 3.x

extra:
  recipe-maintainers:
    - jschueller
