travis:
  secure:
    BINSTAR_TOKEN: IoKt3FnWGyxJH8qeu5TKz3VZuox1K7+/NPr1l1GOMOV+qyODj3tnC4VxQ1p+E81gYRY27JFNYb//Tbtmw/wuVY+vT75vsLjJj6WDWvexDaHXHpp/UMC2PeYfjIZ71b0cKfQmx8KrNCMMXbkkzCmWNb0EoEgP6R3an78tgq/cEHiX9htOc8hSLiuIh/IRA2nSTbElxkSmL2zd18rknDfft0+jXobL/tXit9+YHujQf+uGDb1XVMq7t6Xl9MtjFhEy7EzsfDFmKz8Ybm16eAqEIZ3dquQf+JYlKKPoYN8Z6dNJfRAXApp6R4X9kfDkDKygSJxVy1ZZ4JaNYn2k0igqawxPbML6VBG0YXzaj5zlEqJIU2703X2PgHYhPLsvoLkEdqnIyrvvW+SiRMKs1nCaZJyTFeGPe2Rdpr745vFqUN96ziJEVGAFXZnVQdVZ2Nbfx6W9WkZk+DuU4riW1bg4MwAOyaVV5VgB84SQ3lPcaTItypryOF2gGywFD8KL3njuBaX86t3W2s3dvmW0VJpdokxUGUtqdCkSrcDCjzch4LqI5ysouCRl88kfTCgDF9PH8J20sKctMvxomicrKsv3CgvNUshW7zX+NcgLPNt4GYS9up+almgFJ6HYu5g1J2UiTHWBSOXmcQCWfbYHYK6FM6hS989KICLweY+Q0ecycgE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
